### ISSUE TITLE
episodes not showing

### ISSUE THREAD

**Issue by HalfBloodprinc3** [zarqizoubir/animes#4]
only the loading screen all I can See. JUST TOW SABER FIGHITING WITH EACH OTHER. I WAIT ALMOST 1 HOUR . BUT NOTHING APPEARS. ALSO THE SEARH OPTION DOES NOT WORK PROPERLY

**Comment by regisx001** [comment]
yeah , there is a bug in the api .
unfortunately , i don't have control on the api so i can fix it .
but soon it's gonna fix .

**Comment by HalfBloodprinc3** [comment]
> yeah , there is a bug in the api .
> unfortunately , i don't have control on the api so i can fix it .
> but soon it's gonna fix .

Oooh.... okay....btw....the api is great 👍...keep it up 🤠
